version: '3'
services:

  server:
    build:
      context: ./binaries/services
      dockerfile: Dockerserver
    ports:
      - 8761:8761
    depends_on:
      - db
    volumes:
      - ./XCoLab:/opt/xcolab
    networks:
      - xcolab

  proxy:
    build:
      context: ./binaries/services
      dockerfile: Dockerproxy
    ports:
      - 8765:8765
    depends_on:
      - db
    volumes:
      - ./XCoLab:/opt/xcolab
    networks:
      - xcolab
  admin:
    build:
      context: ./binaries/services
      dockerfile: Dockeradmin
    depends_on:
      - db
    volumes:
      - ./XCoLab:/opt/xcolab
    links:
      - db
    networks:
      - xcolab

  view:
    build:
      context: ./binaries/services
      dockerfile: Dockerview
    ports:
      - 18082:18082
    depends_on:
      - db
    links:
      - admin
    volumes:
      - ./XCoLab:/opt/xcolab
    networks:
      - xcolab
  db:
    image: mysql:5.6
    container_name: xcolabdb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8;'
    ports:
      - 3306:3306
    volumes:
      - '../mysql:/var/lib/mysql'
      - '~/mysql/initdb.d:/docker-entrypoint-initdb.d'
    environment:
      MYSQL_DATABASE: "xcolab"
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "123"
    networks:
      - xcolab
networks:
  xcolab:
